controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController


diff_drive_controller:
  ros__parameters:

    left_wheel_names:
      - left_wheel_joint

    right_wheel_names:
      - right_wheel_joint

    wheel_separation: 0.20        # Distance between wheel centers (m)
    wheel_radius: 0.04            # Wheel radius (m)

    publish_rate: 50.0

    base_frame_id: base_link
    odom_frame_id: odom

    use_stamped_vel: false
    enable_odom_tf: true

    open_loop: true

    position_feedback: true

    cmd_vel_timeout: 0.5

    velocity_rolling_window_size: 10

    pose_covariance_diagonal:
      - 0.001
      - 0.001
      - 1000000.0
      - 1000000.0
      - 1000000.0
      - 0.01

    twist_covariance_diagonal:
      - 0.001
      - 0.001
      - 1000000.0
      - 1000000.0
      - 1000000.0
      - 0.01

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -1.0
        has_acceleration_limits: true
        max_acceleration: 2.0

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0
        min_velocity: -2.0
        has_acceleration_limits: true
        max_acceleration: 4.0